export const STORY_START = "STORY_START";
export const SET_STORIES_START = "SET_STORIES_START";
export const SET_LUCK_STORIES = "SET_LUCK_STORIES";
export const SET_STORIES_ERROR = "SET_STORIES_ERROR";

/* QUOTE ucun */
export const QUOTE_START = "QUOTE_START";
export const SET_QUOTES_START = "SET_QUOTES_START";
export const SET_LUCK_QUOTES = "SET_LUCK_QUOTES";
export const SET_QUOTES_ERROR = "SET_QUOTES_ERROR";
export const HEART_LUCK_STORIES = "HEART_LUCK_STORIES";
export const MARK_LUCK_STORIES = "MARK_LUCK_STORIES";

/* status */
export const STATS_START = "STATS_START";
export const STATS_LUCK_QUOTES = "STATS_LUCK_QUOTES";
export const STATS_QUOTES_ERROR = "STATS_QUOTES_ERROR";
export const DELETE_QUOTES_STATUS = "DELETE_QUOTES_STATUS";
export const DELETE_QUOTES = "DELETE_QUOTES";
export const UPDATE_QUOTE_HEART = "UPDATE_QUOTE_HEART";
export const SET_LUCK_CHANGE_QUOTES = "SET_LUCK_CHANGE_QUOTES";


/* VIDEOS ucun */
export const VİDEO_START = "VİDEO_START";
export const SET_VIDEOS_START = "SET_VIDEOS_START";
export const SET_LUCK_VIDEOS = "SET_LUCK_VIDEOS";
export const SET_VIDEOS_ERROR = "SET_VIDEOS_ERROR";
/* status */
export const STATS_VİDEO_BEGİN = "STATS_VİDEO_BEGİN";
export const STATS_LUCK_VIDEOS = "STATS_LUCK_VIDEOS";
export const STATS_VIDEOS_ERROR = "STATS_VIDEOS_ERROR";
/* FOR ITEM VIDEO */
export const SET_ITEM_VIDEO_START = "SET_ITEM_VIDEO_START";
export const SET_LUCK_ITEM_VIDEO = "SET_LUCK_ITEM_VIDEO";
export const SET_ERROR_ITEM_VIDEO = "SET_ERROR_ITEM_VIDEO";
export const ITEM_VIDEO_START = "ITEM_VIDEO_START";
export const DELETE_ITEM_VIDEO = "DELETE_ITEM_VIDEO";
export const DELETE_VIDEOS_STATUS = "DELETE_VIDEOS_STATUS";
export const DELETE_VIDEOS = "DELETE_VIDEOS";
export const UPDATE_ITEM_HEART_VIDEO = "UPDATE_ITEM_HEART_VIDEO";
export const UPDATE_ITEM_MARK_VIDEO = "UPDATE_ITEM_MARK_VIDEO";

/* MOVIES ucun */
export const MOVIE_START = "MOVIE_START";
export const SET_MOVIES_START = "SET_MOVIES_START";
export const SET_LUCK_MOVIES = "SET_LUCK_MOVIES";
export const SET_MOVIES_ERROR = "SET_MOVIES_ERROR";
/* status */
export const STATS_MOVIE_BEGİN = "STATS_MOVIE_BEGİN";
export const STATS_LUCK_MOVIES = "STATS_LUCK_MOVIES";
export const STATS_MOVIES_ERROR = "STATS_MOVIES_ERROR";
/* FOR ITEM MOVIE */
export const SET_ITEM_MOVIE_START = "SET_ITEM_MOVIE_START";
export const SET_LUCK_ITEM_MOVIE = "SET_LUCK_ITEM_MOVIE";
export const SET_ERROR_ITEM_MOVIE = "SET_ERROR_ITEM_MOVIE";
export const ITEM_MOVIE_START = "ITEM_MOVIE_START";
export const DELETE_ITEM_MOVIE = "DELETE_ITEM_MOVIE";
export const DELETE_MOVIES_STATUS = "DELETE_MOVIES_STATUS";
export const DELETE_MOVIES = "DELETE_MOVIES";
export const UPDATE_ITEM_HEART_MOVIE = "UPDATE_ITEM_HEART_MOVIE";
export const UPDATE_ITEM_MARK_MOVIE = "UPDATE_ITEM_MARK_MOVIE";


/* EVENT ucun */
export const EVENT_START = "EVENT_START";
export const SET_EVENTS_START = "SET_EVENTS_START";
export const SET_LUCK_EVENTS = "SET_LUCK_EVENTS";
export const SET_EVENTS_ERROR = "SET_EVENTS_ERROR";
export const DELETE_EVENTS = "DELETE_EVENTS";

export const BESTS_INIT = "BESTS_INIT";
export const SET_BESTS_START = "SET_BESTS_START";
export const SET_BESTS_LUCK = "SET_BESTS_LUCK";
export const SET_BESTS_ERROR = "SET_BESTS_ERROR";
export const UPDATE_BESTS_HEART = "UPDATE_BESTS_HEART";
export const DELETE_BESTS = "DELETE_BESTS";
export const DELETE_BESTS_STATUS = "DELETE_BESTS_STATUS";

export const SET_LUCK_CHANGE_BESTS = "SET_LUCK_CHANGE_BESTS";
/* status */
export const STATS_BEST_BEGİN = "STATS_BEST_BEGİN";
export const STATS_LUCK_BESTS = "STATS_LUCK_BESTS";
export const STATS_BESTS_ERROR = "STATS_BESTS_ERROR";